server:
  port: 3000
eureka:
  client:
    service-url:
      defaultZone: http://192.168.150.131:7001/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: cloud-common