server:
  port: 80

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        #       account
        - id: account
          uri: lb://CLOUD-ACCOUNT
          predicates:
            - Path=/account/**
          filters:
            - RewritePath=/account/(?<segment>.*), /$\{segment}
        #       common
        - id: common
          uri: lb://CLOUD-COMMON
          predicates:
            - Path=/common/**
          filters:
            - RewritePath=/common/(?<segment>.*), /$\{segment}
        #       order
        - id: order
          uri: lb://CLOUD-ORDERS
          predicates:
            - Path=/order/**
          filters:
            - RewritePath=/order/(?<segment>.*), /$\{segment}

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 3
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: cloud-gateway
    prefer-ip-address: true
key:
  public: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAIZAqCz5TQeb2z6GzN9jZB8fiJrFQRSUjO9EDtKBoJRjdeintP8dSgSihsQzmZUfNixURizGM1SSKdv/t9xRcJ8CAwEAAQ==