server:
  port: 3002
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: cloud-orders
spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  datasource:
    username: root
    password: password
    url: jdbc:mysql://192.168.150.128/cloud-order
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    port: 6379
    database: 1
    host: 192.168.150.128
    password: password

logging:
  level:
    com:
      github:
        tanyueran:
          mapper: debug

key:
  public: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAIZAqCz5TQeb2z6GzN9jZB8fiJrFQRSUjO9EDtKBoJRjdeintP8dSgSihsQzmZUfNixURizGM1SSKdv/t9xRcJ8CAwEAAQ==